### ISSUE TITLE
Possible Windows support?

### ISSUE THREAD

**Issue by CodeF0x** [xvxx/vial#2]
Hi! So far, I like vial a lot! 

However I was wondering if support for Windows is planned? I think that vial would benefit a lot from being cross-platform!

That's all I want to know for now, thanks :).

**Comment by xvxx** [comment]
Hi there, I'm glad you're enjoying Vial!

Vial is the first part of a trilogy of "small" software optimized for development and fast iteration:

1. Web Server
2. HTML Templating Language 
3. Database

To me "small" means:

- Very few dependencies (Vial has 2 direct dependencies and 4 overall)
- Fast build time
- Development ergonomics preferred over runtime performance
- Produces a single file binary (why Vial has asset bundling built-in)

The idea is that you can always move to Rocket or one of the big frameworks if your project grows up, but if you just want to mash your keyboard and hack on something quick you can use Vial and friends.

So that all said, I am open to Windows support, but my current focus is on getting alpha versions of the "trilogy" released, making them all work together nicely, and then stabilizing them. I am pretty close to releasing the zero dependency HTML Templating Language, *Hatter*, hopefully in the next week or so. 

At the current rate, I would probably look into Windows support after all three pieces of software are released, but if you think it would be more helpful to have it sooner, or if you would be personally using it, I can rethink my priorities. (I do have a Windows PC, I just do most of my dev on Mac and Linux.)

Anyway, sorry for the long answer, and thank you for your interest!

**Comment by CodeF0x** [comment]
Hi again!

What you're planning sounds very interesting, I didn't know that! I think you should keep your focus on the things you're already doing, as I don't necessarily need Windows support and your "trilogy" sounds very promising. So please don't feel pressured to do anything out of track and keep up the great work!

I'll close this issue for now, so it doesn't "fly around" idle. 
Thanks for your detailed answer and good luck with Hatter!
